#!/bin/bash

DOCKER_DIR=$(realpath $(dirname $0))
DOCKER_IMAGE=hsm:ane-enclave
THE_BINARY=$DOCKER_DIR/thebinary
THE_CERTIFICATES=$DOCKER_DIR/ca-certificates.crt
FIRMWARE_DIR=$DOCKER_DIR/../../firmware
EIF_OUTPUT_PATH=$DOCKER_DIR/output

print_usage() {
    echo "Usage: $0 [tcpsigner|kmsclient|binary]"
    exit 1
}

if [ -z "$1" ]; then
    print_usage
fi

if [[ "$1" == "tcpsigner" ]]; then
    # Build tcpsigner and target image
    $FIRMWARE_DIR/build/build-tcpsigner-static
    cp -f $FIRMWARE_DIR/src/tcpsigner/tcpsigner $THE_BINARY
    rm -f $THE_CERTIFICATES
elif [[ "$1" == "kmsclient" ]]; then
    $FIRMWARE_DIR/src/kms-client/build vsock
    cp -f $FIRMWARE_DIR/src/kms-client/kms_client $THE_BINARY
    rm -f $THE_CERTIFICATES

    docker run --name tcpstatic-build hsm:tcpstatic
    docker cp tcpstatic-build:/etc/ssl/certs/ca-certificates.crt $THE_CERTIFICATES
    docker rm tcpstatic-build
elif [[ "$1" == "binary" ]]; then
    rm -f $THE_CERTIFICATES
    docker cp tcpstatic-build:/etc/ssl/certs/ca-certificates.crt $THE_CERTIFICATES
else
    print_usage
fi


touch -d@0 $THE_BINARY
touch -d@0 $THE_CERTIFICATES
docker buildx build --build-arg SOURCE_DATE_EPOCH=0 --output type=image,name=$DOCKER_IMAGE,rewrite-timestamp=true --no-cache -f $DOCKER_DIR/Dockerfile.enclave $DOCKER_DIR

# Build EIF builder image
docker build -t eif-builder -f $DOCKER_DIR/Dockerfile.eifbuilder $DOCKER_DIR

# Create output directory (remove any existing directory and contents)
rm -rf $EIF_OUTPUT_PATH
mkdir $EIF_OUTPUT_PATH

# Get local docker socket path
DOCKER_SOCK_PATH=$(docker context inspect | jq -r '.[0].Endpoints.docker.Host' | sed "s^unix://^^")

# Run EIF builder with Docker-in-Docker
docker run -v ${DOCKER_SOCK_PATH}:/var/run/docker.sock -v ${EIF_OUTPUT_PATH}:/output -e DOCKER_IMAGE_TAG=${DOCKER_IMAGE} eif-builder
