# amazonlinux:2023.10.20260105.0
FROM amazonlinux@sha256:808df4d068adf02dadb815bdb32bd2b132ce70260571401adf3ff8a19e99ce82

# Install nitro-cli
RUN dnf install aws-nitro-enclaves-cli aws-nitro-enclaves-cli-devel -y

# Copy builder script
RUN mkdir /scripts
COPY --chmod=770 build-enclave /scripts/

# Artifact directory
WORKDIR /output

ENTRYPOINT ["/scripts/build-enclave"]
