#!/bin/bash

pushd $(dirname $0) > /dev/null
ROOT_DIR=$(pwd)

if [[ $# -lt 4 ]]; then
    echo "Usage: $0 <destination path> <checkpoint> <minimum difficulty> <network>"
    exit 1
fi

DEST_DIR=$1
CHECKPOINT=$2
DIFFICULTY=$3
NETWORK=$4
FIRMWARE_DIR=$DEST_DIR/firmware
BIN_DIR=$DEST_DIR/bin

if [[ -e $DEST_DIR ]]; then
    echo -e "\e[31mDestination directory $DEST_DIR exists"
    exit 1
fi

echo -e "\e[32mBuilding into \e[93m$DEST_DIR\e[32m with checkpoint \e[93m$CHECKPOINT\e[32m, minimum difficulty \e[93m$DIFFICULTY\e[32m and network \e[93m$NETWORK\e[32m...\e[0m"
echo -e "\e[33mCopying files and creating directories...\e[0m"
rm -rf $DEST_DIR
cp -Rf $ROOT_DIR/dist $DEST_DIR

rm -rf $FIRMWARE_DIR
mkdir -p $FIRMWARE_DIR

rm -rf $BIN_DIR
mkdir -p $BIN_DIR

rm -f $DEST_DIR/backup.bin.gpg $DEST_DIR/pin.txt $DEST_DIR/public-keys.txt $DEST_DIR/public.gpg

echo
echo -e "\e[33mBuilding middleware...\e[0m"
$ROOT_DIR/middleware/build/dist
cp $ROOT_DIR/middleware/bin/adm.tgz $BIN_DIR
cp $ROOT_DIR/middleware/bin/lbutils.tgz $BIN_DIR
cp $ROOT_DIR/middleware/bin/manager.tgz $BIN_DIR
cp $ROOT_DIR/middleware/bin/signapp.tgz $BIN_DIR
echo

computeHash() {
    printf "\e[33m$HEX_NAME hash: \e[93m"
    $ROOT_DIR/docker/mware/do-notty-nousb /hsm2 "middleware/bin/signapp/signapp hash -a $HEX_PATH" | \
        grep "App hash:" | \
        sed "s/App hash: //g"
    echo -e "\e[0m"
}

echo -e "\e[33mBuilding signer...\e[0m"
$ROOT_DIR/ledger/build/build-signer $CHECKPOINT $DIFFICULTY $NETWORK > /dev/null
cp $ROOT_DIR/ledger/src/signer/bin/app.hex $FIRMWARE_DIR/signer.hex
cp $ROOT_DIR/ledger/src/signer/icon.hex $FIRMWARE_DIR/signer.icon.hex
HEX_NAME="Signer"
HEX_PATH="ledger/src/signer/bin/app.hex"
computeHash

echo -e "\e[33mBuilding UI...\e[0m"
$ROOT_DIR/ledger/build/build-ui > /dev/null
cp $ROOT_DIR/ledger/src/ui/bin/token.hex $FIRMWARE_DIR/ui.hex
cp $ROOT_DIR/ledger/src/ui/icon.hex $FIRMWARE_DIR/ui.icon.hex
HEX_NAME="UI"
HEX_PATH="ledger/src/ui/bin/token.hex"
computeHash

popd > /dev/null
