#!/bin/bash

# Script directory
pushd $(dirname $0) > /dev/null
MIDDLEWARE_ROOT=$(pwd)
popd > /dev/null

CMD="/bin/bash"
if [[ -n "$@" ]]; then
    CMD="$@"
fi

if [[ ${CI:-false} == true ]]; then
    $MIDDLEWARE_ROOT/../docker/mware/do-notty-nousb /hsm2/middleware "$CMD"
else
    $MIDDLEWARE_ROOT/../docker/mware/do /hsm2/middleware "$CMD"
fi
