#!/bin/bash

# Script directory
pushd $(dirname $0) > /dev/null
MIDDLEWARE_ROOT=$(pwd)
popd > /dev/null

$MIDDLEWARE_ROOT/../docker/mware/do-notty-nousb /hsm2/middleware "python -m unittest discover"
