name: "Middleware coverage"

on:
  push:
  workflow_dispatch:

jobs:
  coverage:
    name: Run tests and generate coverage report
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Build the middleware docker image
        run: docker/mware/build

      - name: Run coverage script
        run: middleware/test-all-coverage

      - name: "Upload coverage report"
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: middleware/coverage
