name: "Static analysis"

on: [push]

# Declare default permissions as read only.
permissions: read-all

jobs:
  static-analysis:
    name: Run static analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Build the ledger docker image
        run: docker/ledger/build

      - name: Build the SGX docker image
        run: docker/sgx/build

      - name: Run static analysis
        id: static-analysis
        run: |
          docker/sgx/do-notty /hsm2/firmware/src/sgx "make generate-private-key"
          firmware/static-analysis/gen-static-analysis
      
      - name: Upload static analysis reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: static-analysis-reports
          path: firmware/static-analysis/output

      - name: Report static analysis findings
        if: steps.static-analysis.outcome != 'success'
        run: |
          echo "Static analysis reported findings. Check static-analysis-reports for a complete report." \
            > $GITHUB_STEP_SUMMARY
